- name: add repository for NginX
  yum:
    name: epel-release
    state: latest

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: reload and enable nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
